remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: AntroxEV - Codes for R&D in Civil Engineering
description: Bookmark this to keep an eye on my project updates!

